version: '3'

services:
  todofrontend:
    image: todofrontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback

  todobackend:
    image: todobackend
    restart: always
    ports:
      -3001:3001

  todotests:
    image: todotests
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
  